# High-level config
attr_names_threshold: 2
cosine_threshold: 0.7
f_vec_directory: db/teleport

# User-level config
model: Candidate
entity: Person
attributes:
    - source:   name
      dest:   name
    - source:   occupation
      dest:   occupation
    - source:   address
      dest:   address
    - source:   phone
      dest:   phone
